### ISSUE TITLE
Uploads do not resume

### ISSUE THREAD

**Issue by davidgourde** [tus/tus-jquery-client#11]
I start an upload of a large file (1GB) and let it upload until half is done. At that point, I close the tab and open a new one. I upload the same file again and receive this error:

`:1080/files/d6995cb33a1af62ed3d773b85f83f18a?_=1470920397045:1 HEAD http://localhost:1080/files/d6995cb33a1af62ed3d773b85f83f18a?_=1470920397045 404 (Not Found)`

And it starts the upload process again from the start.

I am using `tus-node-server` and I am serving the demo of `tus-jquery-client` with node `http-server` command.

This is the messages in the terminal from the `tus-node-server`:

```
[14:58:36] tus server listening at http://127.0.0.1:1080 using FileStore
[TusServer] handle: OPTIONS /files/
[TusServer] handle: POST /files/
[TusServer] handle: OPTIONS /files/d6995cb33a1af62ed3d773b85f83f18a
[TusServer] handle: PATCH /files/d6995cb33a1af62ed3d773b85f83f18a
[TusServer] handle: OPTIONS /files/d6995cb33a1af62ed3d773b85f83f18a?_=1470920397
045
[TusServer] handle: HEAD /files/d6995cb33a1af62ed3d773b85f83f18a?_=1470920397045

[FileStore] getOffset: No file found at files/d6995cb33a1af62ed3d773b85f83f18a?_
=1470920397045
[HeadHandler] { status_code: 404,
  body: 'The file for this url was not found\n' }
[TusServer] handle: OPTIONS /files/
[TusServer] handle: POST /files/
[TusServer] handle: OPTIONS /files/c2505988e7bd533b2ab745dfe1266411
[TusServer] handle: PATCH /files/c2505988e7bd533b2ab745dfe1266411
```

**Comment by bhstahl** [comment]
This should be a result of `tus-node-server` [missing the `Access-Control-Expose-Headers` header](https://github.com/tus/tus-node-server/issues/42#issuecomment-239176729). Will fix there then have you retry @davidgourde, sound good?

**Comment by davidgourde** [comment]
Hum, I still have the same problem. I used the latest version of `tus-node-server` and` tus-jquery-client` to test.

**Comment by davidgourde** [comment]
Sounds good.

**Comment by davidgourde** [comment]
Sounds good, I will try again when it is fixed on the Node server.
