### ISSUE TITLE
any method to resume paused upload?

### ISSUE THREAD

**Issue by kevin-netsrik** [tus/tus-jquery-client#12]
i found this very useful for me, however, is there any way to resume paused upload?

i have tried to use _start() (by rename it as start()) but not help.

hope to have your reply

**Comment by Acconut** [comment]
I am sorry but I cannot fully follow your issue. What do you mean with a paused upload? In theory, the client should continue an interrupted upload if the same file is selected again.
However, I would absolutely recommend against using the jQuery client as it is not maintained actively anymore. Instead the [tus-js-client](https://github.com/tus/tus-js-client) is the current and most feature-rich library for browser environments.

**Comment by kevin-openc** [comment]
thanks for your reply, yes, i would like to resume a paused upload after the stop().
thanks for your reply and i will try to use tus-js-client instead!

**Comment by Acconut** [comment]
> i would like to resume a paused upload after the stop().

As I said, the client should continue an interrupted upload if the same file is selected again. In addition, you should be able to manually trigger a start using the `tus.upload` method: https://github.com/tus/tus-jquery-client/blob/master/js/jquery.tus.js#L33

> i will try to use tus-js-client instead!

Great! I will close this issue for now. If you have any questions regarding tus-js-client, please open a ticket in its repository.
